# This is the network config written by 'subiquity'
network:
  version: 2
  renderer: networkd
  ethernets:
    ens160:
      dhcp4: false
      addresses:
        - 172.16.50.3/29
      routes:
        - to: 0.0.0.0/0
          via: 172.16.50.2
      nameservers:
        addresses:
          - 172.16.50.2
  version: 2
